alias hput='hadoop fs -put'
alias hrm='hadoop fs -rm'
alias hrmr='hadoop fs -rm -r'
alias hfs='hadoop fs'
alias hls='hadoop fs -ls'

alias yarnlogs='yarn logs -applicationId'
alias yarnmonitor='watch yarn application -list'
alias yarnlist='yarn application -list'

restart () {

    case $1 in
        all)
            CMD="sudo service mapr-warden restart"
        ;;
        nm)
            CMD="sudo -u mapr maprcli node services -name nodemanager -action restart -nodes `hostname`"
        ;;
        rm)
            CMD="sudo -u mapr maprcli node services -name resourcemanager -action restart -nodes `hostname`"
        ;;
    esac

   $CMD
}

export -f restart